### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by iamvdo** [tzi/ChewingGrid#4]
Hey Thomas!

First, thanks for this great grid. First time I use it and I already love it.

Here's my feedback:

I noticed a difference between Firefox and Chrome when using `min-width` in `.chew-cell` elements (from your demo here: http://tzi.github.io/chewing-grid.css/demo.html). In Chrome, elements do have the same size while in Firefox they don't. Using `flex-basis` solves the "problem" (if we assume that it's a problem).

I spend few minutes to understand why elements on last row don't expand to fill the space (or why alignment was messed up when using `justify-content` on parent), then I discovered that `.chew-card` elements have `max-width: 300px` by default. It's not clearly explained in doc, maybe it's worth adding it or removing `max-width` by default? I could also have read more carefully the CSS. ;)

Related to this, I also noticed that alignment on parent (with `justify-content`) only works if `.chew-cell` elements have a `max-width`. I'm not sure if it's normal or not.

**Comment by tzi** [comment]
Hey Vincent!

Thanks a lot for the feedback ;)

**1/ Flex-basis**
Flexbox implementations are not stable. So I'm not really surprised of the difference between Firefox & Chrome. I don't use `flex-basis` because IE10-11 doesn't support `border-box: content-box` with `flex-basis`. I actually documented it [here](https://github.com/tzi/chewing-grid.css/blob/master/DOCUMENTATION.md#browser-compatibility).

**2/ Max-width**
You're right, I will remove the default `max-width` on the `.chew-card`. The `max-width` is not on the flex elements to handle the gutter.
The better solution is to set the gutter with `margins` instead of `padding`. So you have to use `calc()` function to set the default cell width, for example `width: calc(20% - 1em)` for a 5 columns with 1em gutter. This way you can set up `max-width` directly on flex elements.
I didn't done that because of another IE10-11 bug with `calc()` function and flex item. 

**3/ Justify-content**
Because every flex item has a positive`flex-grow`, it will always take the all line width. So you can not use `justify-content` to handle the alignment. It also makes sense it works if you apply a `max-width` on flex items.
The better option is perhaps to solve your second point to be able to use `justify-content`.
I wonder if It would be better to drop IE10-11 support for this grid, like what I have done for all Safari browsers.

Thanks again!
Thomas.

**Comment by iamvdo** [comment]
Hey.

**1. Flex-basis**
Oh yes, I've read the "browser compatibility" section, but it was not a problem for me, so I forgot. ;)

**2. max-width**

> The better solution is to set the gutter with margins instead of padding

I'm not sure. Using `padding` is great, but `max-width` on `.chew-card` elements sometimes create bigger gutters. In fact, I didn't realize that `max-width` was set, and so, bigger gutters have appeared.

**3. justify-content**
Same here, flex items always take the line width, right, but when `.chew-card` elements have a `max-width`, it seems it's not.

As a result, my main problem here was the `max-width` issue. ;)

**Comment by iamvdo** [comment]
> IE10-11 doesn't support `border-box: content-box` with flex-basis

I think you mean the opposite ;)

**Comment by tzi** [comment]
What do you like about gutter with `padding` instead of `margin`?

I've removed the default `max-width` on chewing card.
I packaged a new version: 3.1.0
So I'll close this issue ;)

Thanks again for your feedback,
Thomas.

**Comment by iamvdo** [comment]
> What do you like about gutter with padding instead of margin?

Nothing. I have no preferences. Maybe `margin` is more straigthforward, you're right.
